services:
  - type: worker
    name: cool_kid_bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: BOT_TOKEN
        value: 7848063287:AAHz4qDiPXxmPzFuYulwjEsKUhKkeqki5Mk
